# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "minitest", "~> 5.0"
gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"
gem "rb_sys", "~> 0.9"
gem "standard", "~> 1.0"
gem "rubocop-minitest", "~> 0.36"
