# frozen_string_literal: true

# Build tasks for the iscc-lib Ruby gem.
# Uses rb_sys to compile the Rust native extension via Cargo.

require "rake/testtask"
require "rb_sys/extensiontask"

GEMSPEC = Gem::Specification.load("iscc-lib.gemspec")

RbSys::ExtensionTask.new("iscc-rb", GEMSPEC) do |ext|
  ext.lib_dir = "lib/iscc_lib"
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/test_*.rb"]
end

task default: %i[compile test]
