// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(iscc_uniffiFFI)
import iscc_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_iscc_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_iscc_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureIsccUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Streaming Data-Code generator.
 *
 * Incrementally processes data with content-defined chunking and MinHash.
 * Call `update()` with data chunks, then `finalize()` to produce the code.
 */
public protocol DataHasherProtocol: AnyObject, Sendable {

    /**
     * Consume the inner hasher and produce a Data-Code result.
     */
    func finalize(bits: UInt32) throws  -> DataCodeResult

    /**
     * Push data into the hasher.
     */
    func update(data: Data) throws

}
/**
 * Streaming Data-Code generator.
 *
 * Incrementally processes data with content-defined chunking and MinHash.
 * Call `update()` with data chunks, then `finalize()` to produce the code.
 */
open class DataHasher: DataHasherProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_iscc_uniffi_fn_clone_datahasher(self.handle, $0) }
    }
    /**
     * Create a new `DataHasher`.
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_iscc_uniffi_fn_constructor_datahasher_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_iscc_uniffi_fn_free_datahasher(handle, $0) }
    }




    /**
     * Consume the inner hasher and produce a Data-Code result.
     */
open func finalize(bits: UInt32)throws  -> DataCodeResult  {
    return try  FfiConverterTypeDataCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_method_datahasher_finalize(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(bits),$0
    )
})
}

    /**
     * Push data into the hasher.
     */
open func update(data: Data)throws   {try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_method_datahasher_update(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(data),$0
    )
}
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataHasher: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = DataHasher

    public static func lift(_ handle: UInt64) throws -> DataHasher {
        return DataHasher(unsafeFromHandle: handle)
    }

    public static func lower(_ value: DataHasher) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataHasher {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DataHasher, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataHasher_lift(_ handle: UInt64) throws -> DataHasher {
    return try FfiConverterTypeDataHasher.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataHasher_lower(_ value: DataHasher) -> UInt64 {
    return FfiConverterTypeDataHasher.lower(value)
}






/**
 * Streaming Instance-Code generator.
 *
 * Incrementally hashes data with BLAKE3 to produce an Instance-Code.
 * Call `update()` with data chunks, then `finalize()` to produce the code.
 */
public protocol InstanceHasherProtocol: AnyObject, Sendable {

    /**
     * Consume the inner hasher and produce an Instance-Code result.
     */
    func finalize(bits: UInt32) throws  -> InstanceCodeResult

    /**
     * Push data into the hasher.
     */
    func update(data: Data) throws

}
/**
 * Streaming Instance-Code generator.
 *
 * Incrementally hashes data with BLAKE3 to produce an Instance-Code.
 * Call `update()` with data chunks, then `finalize()` to produce the code.
 */
open class InstanceHasher: InstanceHasherProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_iscc_uniffi_fn_clone_instancehasher(self.handle, $0) }
    }
    /**
     * Create a new `InstanceHasher`.
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_iscc_uniffi_fn_constructor_instancehasher_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_iscc_uniffi_fn_free_instancehasher(handle, $0) }
    }




    /**
     * Consume the inner hasher and produce an Instance-Code result.
     */
open func finalize(bits: UInt32)throws  -> InstanceCodeResult  {
    return try  FfiConverterTypeInstanceCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_method_instancehasher_finalize(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(bits),$0
    )
})
}

    /**
     * Push data into the hasher.
     */
open func update(data: Data)throws   {try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_method_instancehasher_update(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(data),$0
    )
}
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInstanceHasher: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = InstanceHasher

    public static func lift(_ handle: UInt64) throws -> InstanceHasher {
        return InstanceHasher(unsafeFromHandle: handle)
    }

    public static func lower(_ value: InstanceHasher) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InstanceHasher {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: InstanceHasher, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceHasher_lift(_ handle: UInt64) throws -> InstanceHasher {
    return try FfiConverterTypeInstanceHasher.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceHasher_lower(_ value: InstanceHasher) -> UInt64 {
    return FfiConverterTypeInstanceHasher.lower(value)
}




/**
 * Result of `gen_audio_code_v0`.
 */
public struct AudioCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String) {
        self.iscc = iscc
    }




}

#if compiler(>=6)
extension AudioCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioCodeResult {
        return
            try AudioCodeResult(
                iscc: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AudioCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioCodeResult_lift(_ buf: RustBuffer) throws -> AudioCodeResult {
    return try FfiConverterTypeAudioCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioCodeResult_lower(_ value: AudioCodeResult) -> RustBuffer {
    return FfiConverterTypeAudioCodeResult.lower(value)
}


/**
 * Result of `gen_data_code_v0`.
 */
public struct DataCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String) {
        self.iscc = iscc
    }




}

#if compiler(>=6)
extension DataCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataCodeResult {
        return
            try DataCodeResult(
                iscc: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DataCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataCodeResult_lift(_ buf: RustBuffer) throws -> DataCodeResult {
    return try FfiConverterTypeDataCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataCodeResult_lower(_ value: DataCodeResult) -> RustBuffer {
    return FfiConverterTypeDataCodeResult.lower(value)
}


/**
 * Result of `iscc_decode`.
 */
public struct DecodeResult: Equatable, Hashable {
    /**
     * Main type identifier.
     */
    public var maintype: UInt8
    /**
     * Sub type identifier.
     */
    public var subtype: UInt8
    /**
     * Version number.
     */
    public var version: UInt8
    /**
     * Bit length indicator.
     */
    public var length: UInt8
    /**
     * Raw digest bytes.
     */
    public var digest: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Main type identifier.
         */maintype: UInt8,
        /**
         * Sub type identifier.
         */subtype: UInt8,
        /**
         * Version number.
         */version: UInt8,
        /**
         * Bit length indicator.
         */length: UInt8,
        /**
         * Raw digest bytes.
         */digest: Data) {
        self.maintype = maintype
        self.subtype = subtype
        self.version = version
        self.length = length
        self.digest = digest
    }




}

#if compiler(>=6)
extension DecodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecodeResult {
        return
            try DecodeResult(
                maintype: FfiConverterUInt8.read(from: &buf),
                subtype: FfiConverterUInt8.read(from: &buf),
                version: FfiConverterUInt8.read(from: &buf),
                length: FfiConverterUInt8.read(from: &buf),
                digest: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: DecodeResult, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.maintype, into: &buf)
        FfiConverterUInt8.write(value.subtype, into: &buf)
        FfiConverterUInt8.write(value.version, into: &buf)
        FfiConverterUInt8.write(value.length, into: &buf)
        FfiConverterData.write(value.digest, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodeResult_lift(_ buf: RustBuffer) throws -> DecodeResult {
    return try FfiConverterTypeDecodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodeResult_lower(_ value: DecodeResult) -> RustBuffer {
    return FfiConverterTypeDecodeResult.lower(value)
}


/**
 * Result of `gen_image_code_v0`.
 */
public struct ImageCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String) {
        self.iscc = iscc
    }




}

#if compiler(>=6)
extension ImageCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageCodeResult {
        return
            try ImageCodeResult(
                iscc: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ImageCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageCodeResult_lift(_ buf: RustBuffer) throws -> ImageCodeResult {
    return try FfiConverterTypeImageCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageCodeResult_lower(_ value: ImageCodeResult) -> RustBuffer {
    return FfiConverterTypeImageCodeResult.lower(value)
}


/**
 * Result of `gen_instance_code_v0`.
 */
public struct InstanceCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String
    /**
     * Hex-encoded BLAKE3 multihash of the input data.
     */
    public var datahash: String
    /**
     * Byte length of the input data.
     */
    public var filesize: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String,
        /**
         * Hex-encoded BLAKE3 multihash of the input data.
         */datahash: String,
        /**
         * Byte length of the input data.
         */filesize: UInt64) {
        self.iscc = iscc
        self.datahash = datahash
        self.filesize = filesize
    }




}

#if compiler(>=6)
extension InstanceCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInstanceCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InstanceCodeResult {
        return
            try InstanceCodeResult(
                iscc: FfiConverterString.read(from: &buf),
                datahash: FfiConverterString.read(from: &buf),
                filesize: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: InstanceCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
        FfiConverterString.write(value.datahash, into: &buf)
        FfiConverterUInt64.write(value.filesize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceCodeResult_lift(_ buf: RustBuffer) throws -> InstanceCodeResult {
    return try FfiConverterTypeInstanceCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceCodeResult_lower(_ value: InstanceCodeResult) -> RustBuffer {
    return FfiConverterTypeInstanceCodeResult.lower(value)
}


/**
 * Result of `gen_iscc_code_v0`.
 */
public struct IsccCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String) {
        self.iscc = iscc
    }




}

#if compiler(>=6)
extension IsccCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIsccCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IsccCodeResult {
        return
            try IsccCodeResult(
                iscc: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: IsccCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIsccCodeResult_lift(_ buf: RustBuffer) throws -> IsccCodeResult {
    return try FfiConverterTypeIsccCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIsccCodeResult_lower(_ value: IsccCodeResult) -> RustBuffer {
    return FfiConverterTypeIsccCodeResult.lower(value)
}


/**
 * Result of `gen_meta_code_v0`.
 */
public struct MetaCodeResult: Equatable, Hashable {
    /**
     * ISCC code string (e.g., `"ISCC:AAAZXZ6OU74YAZIM"`).
     */
    public var iscc: String
    /**
     * Normalized name after cleaning, newline removal, and trimming.
     */
    public var name: String
    /**
     * Normalized description (present only when description was non-empty).
     */
    public var description: String?
    /**
     * Metadata as a Data-URL string (present only when meta was provided).
     */
    public var meta: String?
    /**
     * Hex-encoded BLAKE3 multihash of the metadata payload.
     */
    public var metahash: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string (e.g., `"ISCC:AAAZXZ6OU74YAZIM"`).
         */iscc: String,
        /**
         * Normalized name after cleaning, newline removal, and trimming.
         */name: String,
        /**
         * Normalized description (present only when description was non-empty).
         */description: String?,
        /**
         * Metadata as a Data-URL string (present only when meta was provided).
         */meta: String?,
        /**
         * Hex-encoded BLAKE3 multihash of the metadata payload.
         */metahash: String) {
        self.iscc = iscc
        self.name = name
        self.description = description
        self.meta = meta
        self.metahash = metahash
    }




}

#if compiler(>=6)
extension MetaCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMetaCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MetaCodeResult {
        return
            try MetaCodeResult(
                iscc: FfiConverterString.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                description: FfiConverterOptionString.read(from: &buf),
                meta: FfiConverterOptionString.read(from: &buf),
                metahash: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MetaCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
        FfiConverterOptionString.write(value.meta, into: &buf)
        FfiConverterString.write(value.metahash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMetaCodeResult_lift(_ buf: RustBuffer) throws -> MetaCodeResult {
    return try FfiConverterTypeMetaCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMetaCodeResult_lower(_ value: MetaCodeResult) -> RustBuffer {
    return FfiConverterTypeMetaCodeResult.lower(value)
}


/**
 * Result of `gen_mixed_code_v0`.
 */
public struct MixedCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String
    /**
     * Input Content-Code strings (passed through unchanged).
     */
    public var parts: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String,
        /**
         * Input Content-Code strings (passed through unchanged).
         */parts: [String]) {
        self.iscc = iscc
        self.parts = parts
    }




}

#if compiler(>=6)
extension MixedCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMixedCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MixedCodeResult {
        return
            try MixedCodeResult(
                iscc: FfiConverterString.read(from: &buf),
                parts: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: MixedCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
        FfiConverterSequenceString.write(value.parts, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMixedCodeResult_lift(_ buf: RustBuffer) throws -> MixedCodeResult {
    return try FfiConverterTypeMixedCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMixedCodeResult_lower(_ value: MixedCodeResult) -> RustBuffer {
    return FfiConverterTypeMixedCodeResult.lower(value)
}


/**
 * Result of `gen_sum_code_v0`.
 */
public struct SumCodeResult: Equatable, Hashable {
    /**
     * Composite ISCC-CODE string.
     */
    public var iscc: String
    /**
     * Hex-encoded BLAKE3 multihash of the file.
     */
    public var datahash: String
    /**
     * Byte length of the file.
     */
    public var filesize: UInt64
    /**
     * Individual ISCC strings at the requested precision (when `add_units` is true).
     */
    public var units: [String]?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Composite ISCC-CODE string.
         */iscc: String,
        /**
         * Hex-encoded BLAKE3 multihash of the file.
         */datahash: String,
        /**
         * Byte length of the file.
         */filesize: UInt64,
        /**
         * Individual ISCC strings at the requested precision (when `add_units` is true).
         */units: [String]?) {
        self.iscc = iscc
        self.datahash = datahash
        self.filesize = filesize
        self.units = units
    }




}

#if compiler(>=6)
extension SumCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSumCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SumCodeResult {
        return
            try SumCodeResult(
                iscc: FfiConverterString.read(from: &buf),
                datahash: FfiConverterString.read(from: &buf),
                filesize: FfiConverterUInt64.read(from: &buf),
                units: FfiConverterOptionSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: SumCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
        FfiConverterString.write(value.datahash, into: &buf)
        FfiConverterUInt64.write(value.filesize, into: &buf)
        FfiConverterOptionSequenceString.write(value.units, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSumCodeResult_lift(_ buf: RustBuffer) throws -> SumCodeResult {
    return try FfiConverterTypeSumCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSumCodeResult_lower(_ value: SumCodeResult) -> RustBuffer {
    return FfiConverterTypeSumCodeResult.lower(value)
}


/**
 * Result of `gen_text_code_v0`.
 */
public struct TextCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String
    /**
     * Character count after `text_collapse` (u64 because UniFFI doesn't support usize).
     */
    public var characters: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String,
        /**
         * Character count after `text_collapse` (u64 because UniFFI doesn't support usize).
         */characters: UInt64) {
        self.iscc = iscc
        self.characters = characters
    }




}

#if compiler(>=6)
extension TextCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTextCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TextCodeResult {
        return
            try TextCodeResult(
                iscc: FfiConverterString.read(from: &buf),
                characters: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TextCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
        FfiConverterUInt64.write(value.characters, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextCodeResult_lift(_ buf: RustBuffer) throws -> TextCodeResult {
    return try FfiConverterTypeTextCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTextCodeResult_lower(_ value: TextCodeResult) -> RustBuffer {
    return FfiConverterTypeTextCodeResult.lower(value)
}


/**
 * Result of `gen_video_code_v0`.
 */
public struct VideoCodeResult: Equatable, Hashable {
    /**
     * ISCC code string.
     */
    public var iscc: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ISCC code string.
         */iscc: String) {
        self.iscc = iscc
    }




}

#if compiler(>=6)
extension VideoCodeResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVideoCodeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VideoCodeResult {
        return
            try VideoCodeResult(
                iscc: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: VideoCodeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.iscc, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVideoCodeResult_lift(_ buf: RustBuffer) throws -> VideoCodeResult {
    return try FfiConverterTypeVideoCodeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVideoCodeResult_lower(_ value: VideoCodeResult) -> RustBuffer {
    return FfiConverterTypeVideoCodeResult.lower(value)
}


/**
 * UniFFI-compatible error type wrapping `iscc_lib::IsccError`.
 */
public enum IsccUniError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    /**
     * ISCC operation error with a descriptive message.
     */
    case IsccError(
        /**
         * Error description.
         */msg: String
    )






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension IsccUniError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIsccUniError: FfiConverterRustBuffer {
    typealias SwiftType = IsccUniError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IsccUniError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .IsccError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IsccUniError, into buf: inout [UInt8]) {
        switch value {





        case let .IsccError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIsccUniError_lift(_ buf: RustBuffer) throws -> IsccUniError {
    return try FfiConverterTypeIsccUniError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIsccUniError_lower(_ value: IsccUniError) -> RustBuffer {
    return FfiConverterTypeIsccUniError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt32: FfiConverterRustBuffer {
    typealias SwiftType = [Int32]

    public static func write(_ value: [Int32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int32] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceInt32: FfiConverterRustBuffer {
    typealias SwiftType = [[Int32]]

    public static func write(_ value: [[Int32]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[Int32]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[Int32]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceInt32.read(from: &buf))
        }
        return seq
    }
}
/**
 * Split data into content-defined chunks.
 */
public func algCdcChunks(data: Data, utf32: Bool, avgChunkSize: UInt32)throws  -> [Data]  {
    return try  FfiConverterSequenceData.lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_alg_cdc_chunks(
        FfiConverterData.lower(data),
        FfiConverterBool.lower(utf32),
        FfiConverterUInt32.lower(avgChunkSize),$0
    )
})
}
/**
 * Compute a 256-bit MinHash from a set of u32 features.
 */
public func algMinhash256(features: [UInt32]) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_alg_minhash_256(
        FfiConverterSequenceUInt32.lower(features),$0
    )
})
}
/**
 * Compute a SimHash from a collection of hash digests.
 */
public func algSimhash(hashDigests: [Data])throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_alg_simhash(
        FfiConverterSequenceData.lower(hashDigests),$0
    )
})
}
/**
 * Run the conformance self-test against vendored test vectors.
 */
public func conformanceSelftest() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_conformance_selftest($0
    )
})
}
/**
 * Encode binary data as URL-safe base64 (no padding).
 */
public func encodeBase64(data: Data) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_encode_base64(
        FfiConverterData.lower(data),$0
    )
})
}
/**
 * Encode header and digest into an ISCC component string.
 */
public func encodeComponent(mtype: UInt8, stype: UInt8, version: UInt8, bitLength: UInt32, digest: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_encode_component(
        FfiConverterUInt8.lower(mtype),
        FfiConverterUInt8.lower(stype),
        FfiConverterUInt8.lower(version),
        FfiConverterUInt32.lower(bitLength),
        FfiConverterData.lower(digest),$0
    )
})
}
/**
 * Generate an Audio-Code from a chromaprint fingerprint.
 */
public func genAudioCodeV0(cv: [Int32], bits: UInt32)throws  -> AudioCodeResult  {
    return try  FfiConverterTypeAudioCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_audio_code_v0(
        FfiConverterSequenceInt32.lower(cv),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Generate a Data-Code from raw byte data.
 */
public func genDataCodeV0(data: Data, bits: UInt32)throws  -> DataCodeResult  {
    return try  FfiConverterTypeDataCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_data_code_v0(
        FfiConverterData.lower(data),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Generate an Image-Code from raw pixel data.
 */
public func genImageCodeV0(pixels: Data, bits: UInt32)throws  -> ImageCodeResult  {
    return try  FfiConverterTypeImageCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_image_code_v0(
        FfiConverterData.lower(pixels),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Generate an Instance-Code from raw byte data.
 */
public func genInstanceCodeV0(data: Data, bits: UInt32)throws  -> InstanceCodeResult  {
    return try  FfiConverterTypeInstanceCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_instance_code_v0(
        FfiConverterData.lower(data),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Generate a composite ISCC-CODE from multiple code strings.
 */
public func genIsccCodeV0(codes: [String], wide: Bool)throws  -> IsccCodeResult  {
    return try  FfiConverterTypeIsccCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_iscc_code_v0(
        FfiConverterSequenceString.lower(codes),
        FfiConverterBool.lower(wide),$0
    )
})
}
/**
 * Generate a Meta-Code from name, optional description, and optional metadata.
 */
public func genMetaCodeV0(name: String, description: String?, meta: String?, bits: UInt32)throws  -> MetaCodeResult  {
    return try  FfiConverterTypeMetaCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_meta_code_v0(
        FfiConverterString.lower(name),
        FfiConverterOptionString.lower(description),
        FfiConverterOptionString.lower(meta),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Generate a Mixed-Code from multiple content code strings.
 */
public func genMixedCodeV0(codes: [String], bits: UInt32)throws  -> MixedCodeResult  {
    return try  FfiConverterTypeMixedCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_mixed_code_v0(
        FfiConverterSequenceString.lower(codes),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Generate a complete ISCC-SUM from a file path.
 */
public func genSumCodeV0(path: String, bits: UInt32, wide: Bool, addUnits: Bool)throws  -> SumCodeResult  {
    return try  FfiConverterTypeSumCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_sum_code_v0(
        FfiConverterString.lower(path),
        FfiConverterUInt32.lower(bits),
        FfiConverterBool.lower(wide),
        FfiConverterBool.lower(addUnits),$0
    )
})
}
/**
 * Generate a Text-Code from text content.
 */
public func genTextCodeV0(text: String, bits: UInt32)throws  -> TextCodeResult  {
    return try  FfiConverterTypeTextCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_text_code_v0(
        FfiConverterString.lower(text),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Generate a Video-Code from per-frame signatures.
 */
public func genVideoCodeV0(frameSigs: [[Int32]], bits: UInt32)throws  -> VideoCodeResult  {
    return try  FfiConverterTypeVideoCodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_gen_video_code_v0(
        FfiConverterSequenceSequenceInt32.lower(frameSigs),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Buffer size in bytes for streaming file reads (4 MB).
 */
public func ioReadSize() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_io_read_size($0
    )
})
}
/**
 * Decode an ISCC unit string into header components and raw digest.
 */
public func isccDecode(iscc: String)throws  -> DecodeResult  {
    return try  FfiConverterTypeDecodeResult_lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_iscc_decode(
        FfiConverterString.lower(iscc),$0
    )
})
}
/**
 * Decompose an ISCC-CODE into individual unit strings.
 */
public func isccDecompose(isccCode: String)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_iscc_decompose(
        FfiConverterString.lower(isccCode),$0
    )
})
}
/**
 * Convert a JSON string to a Data-URL with JCS canonicalization.
 */
public func jsonToDataUrl(json: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_json_to_data_url(
        FfiConverterString.lower(json),$0
    )
})
}
/**
 * Max UTF-8 byte length for description metadata trimming.
 */
public func metaTrimDescription() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_meta_trim_description($0
    )
})
}
/**
 * Max decoded payload size in bytes for the meta element.
 */
public func metaTrimMeta() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_meta_trim_meta($0
    )
})
}
/**
 * Max UTF-8 byte length for name metadata trimming.
 */
public func metaTrimName() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_meta_trim_name($0
    )
})
}
/**
 * Generate character n-grams from text using a sliding window.
 */
public func slidingWindow(seq: String, width: UInt32)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_sliding_window(
        FfiConverterString.lower(seq),
        FfiConverterUInt32.lower(width),$0
    )
})
}
/**
 * Compute a similarity-preserving video hash from per-frame signatures.
 */
public func softHashVideoV0(frameSigs: [[Int32]], bits: UInt32)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeIsccUniError_lift) {
    uniffi_iscc_uniffi_fn_func_soft_hash_video_v0(
        FfiConverterSequenceSequenceInt32.lower(frameSigs),
        FfiConverterUInt32.lower(bits),$0
    )
})
}
/**
 * Clean text by applying NFKC normalization and control-character removal.
 */
public func textClean(text: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_text_clean(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Collapse text for similarity processing (NFD, lowercase, filter).
 */
public func textCollapse(text: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_text_collapse(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Character n-gram width for text content features.
 */
public func textNgramSize() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_text_ngram_size($0
    )
})
}
/**
 * Remove newlines and collapse whitespace runs to single spaces.
 */
public func textRemoveNewlines(text: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_text_remove_newlines(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Trim text to a maximum number of UTF-8 bytes on a word boundary.
 */
public func textTrim(text: String, nbytes: UInt64) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_iscc_uniffi_fn_func_text_trim(
        FfiConverterString.lower(text),
        FfiConverterUInt64.lower(nbytes),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_iscc_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_alg_cdc_chunks() != 47849) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_alg_minhash_256() != 22989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_alg_simhash() != 21273) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_conformance_selftest() != 11319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_encode_base64() != 9010) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_encode_component() != 59640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_audio_code_v0() != 43793) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_data_code_v0() != 28881) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_image_code_v0() != 48752) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_instance_code_v0() != 34639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_iscc_code_v0() != 639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_meta_code_v0() != 39627) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_mixed_code_v0() != 7580) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_sum_code_v0() != 42460) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_text_code_v0() != 16777) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_gen_video_code_v0() != 39557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_io_read_size() != 37026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_iscc_decode() != 12467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_iscc_decompose() != 63757) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_json_to_data_url() != 13818) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_meta_trim_description() != 27949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_meta_trim_meta() != 58429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_meta_trim_name() != 13793) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_sliding_window() != 60980) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_soft_hash_video_v0() != 10500) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_text_clean() != 65070) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_text_collapse() != 65207) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_text_ngram_size() != 47590) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_text_remove_newlines() != 28628) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_func_text_trim() != 45299) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_method_datahasher_finalize() != 29844) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_method_datahasher_update() != 59854) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_method_instancehasher_finalize() != 56495) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_method_instancehasher_update() != 51907) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_constructor_datahasher_new() != 61879) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_iscc_uniffi_checksum_constructor_instancehasher_new() != 15676) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureIsccUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
