// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Iscc.Lib
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "iscc_ffi";





        /// <summary>
        ///  Maximum byte length for the name field after trimming.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_meta_trim_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint iscc_meta_trim_name();

        /// <summary>
        ///  Maximum byte length for the description field after trimming.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_meta_trim_description", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint iscc_meta_trim_description();

        /// <summary>
        ///  Maximum byte length for the meta field payload after decoding.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_meta_trim_meta", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint iscc_meta_trim_meta();

        /// <summary>
        ///  Default read buffer size for streaming I/O (4 MB).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_io_read_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint iscc_io_read_size();

        /// <summary>
        ///  Sliding window width for text n-gram generation.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_text_ngram_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint iscc_text_ngram_size();

        /// <summary>
        ///  Allocate `size` bytes of WASM-side memory.
        ///
        ///  Returns a pointer the host can write into. The host must call
        ///  `iscc_dealloc` to free this memory. Returns a dangling (non-null)
        ///  pointer for `size == 0`.
        ///
        ///  # Safety
        ///
        ///  The caller must ensure `size` bytes are actually needed and must free
        ///  the allocation with `iscc_dealloc(ptr, size)`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_alloc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_alloc(nuint size);

        /// <summary>
        ///  Free `size` bytes of WASM-side memory at `ptr`, previously allocated
        ///  by `iscc_alloc`.
        ///
        ///  No-op if `ptr` is null. Passing `size == 0` is a no-op because
        ///  `iscc_alloc(0)` returns a dangling pointer that was never allocated.
        ///
        ///  # Safety
        ///
        ///  - `ptr` must have been returned by `iscc_alloc(size)` with the same `size`.
        ///  - Each allocation must be freed exactly once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_dealloc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_dealloc(byte* ptr, nuint size);

        /// <summary>
        ///  Generate a Meta-Code from name and optional metadata.
        ///
        ///  # Parameters
        ///
        ///  - `name`: required, null-terminated UTF-8 string
        ///  - `description`: optional (NULL means not provided)
        ///  - `meta`: optional (NULL means not provided)
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  All non-null pointer arguments must point to valid null-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_meta_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_meta_code_v0(byte* name, byte* description, byte* meta, uint bits);

        /// <summary>
        ///  Generate a Text-Code from plain text content.
        ///
        ///  # Parameters
        ///
        ///  - `text`: required, null-terminated UTF-8 string
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `text` must point to a valid null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_text_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_text_code_v0(byte* text, uint bits);

        /// <summary>
        ///  Generate an Image-Code from pixel data.
        ///
        ///  # Parameters
        ///
        ///  - `pixels`: pointer to 1024 grayscale pixel values (32x32)
        ///  - `pixels_len`: number of bytes in the pixel buffer
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `pixels` must point to a valid buffer of at least `pixels_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_image_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_image_code_v0(byte* pixels, nuint pixels_len, uint bits);

        /// <summary>
        ///  Generate an Audio-Code from a Chromaprint feature vector.
        ///
        ///  # Parameters
        ///
        ///  - `cv`: pointer to signed 32-bit integer Chromaprint features
        ///  - `cv_len`: number of elements in the feature vector
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `cv` must point to a valid buffer of at least `cv_len` `i32` elements.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_audio_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_audio_code_v0(int* cv, nuint cv_len, uint bits);

        /// <summary>
        ///  Generate a Video-Code from frame signature data.
        ///
        ///  # Parameters
        ///
        ///  - `frame_sigs`: array of pointers to frame signature arrays
        ///  - `frame_lens`: array of lengths for each frame signature
        ///  - `num_frames`: number of frames
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  - `frame_sigs` must point to an array of `num_frames` valid pointers
        ///  - `frame_lens` must point to an array of `num_frames` lengths
        ///  - Each `frame_sigs[i]` must be valid for `frame_lens[i]` `i32` elements
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_video_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_video_code_v0(int** frame_sigs, nuint* frame_lens, nuint num_frames, uint bits);

        /// <summary>
        ///  Generate a Mixed-Code from multiple Content-Code strings.
        ///
        ///  # Parameters
        ///
        ///  - `codes`: array of pointers to null-terminated ISCC code strings
        ///  - `num_codes`: number of code strings
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `codes` must point to an array of `num_codes` valid null-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_mixed_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_mixed_code_v0(byte** codes, nuint num_codes, uint bits);

        /// <summary>
        ///  Generate a Data-Code from raw byte data.
        ///
        ///  # Parameters
        ///
        ///  - `data`: pointer to raw byte data
        ///  - `data_len`: number of bytes
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `data` must point to a valid buffer of at least `data_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_data_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_data_code_v0(byte* data, nuint data_len, uint bits);

        /// <summary>
        ///  Generate an Instance-Code from raw byte data.
        ///
        ///  # Parameters
        ///
        ///  - `data`: pointer to raw byte data
        ///  - `data_len`: number of bytes
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `data` must point to a valid buffer of at least `data_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_instance_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_instance_code_v0(byte* data, nuint data_len, uint bits);

        /// <summary>
        ///  Generate a composite ISCC-CODE from individual unit codes.
        ///
        ///  # Parameters
        ///
        ///  - `codes`: array of pointers to null-terminated ISCC unit code strings
        ///  - `num_codes`: number of code strings
        ///  - `wide`: if true and exactly 2 codes (Data+Instance) with 128+ bits, produce wide output
        ///
        ///  # Returns
        ///
        ///  Heap-allocated ISCC string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `codes` must point to an array of `num_codes` valid null-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_iscc_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_gen_iscc_code_v0(byte** codes, nuint num_codes, [MarshalAs(UnmanagedType.U1)] bool wide);

        /// <summary>
        ///  Clean and normalize text for display.
        ///
        ///  Applies NFKC normalization, removes control characters (except newlines),
        ///  normalizes `\r\n` to `\n`, collapses consecutive empty lines, and strips
        ///  leading/trailing whitespace.
        ///
        ///  # Returns
        ///
        ///  Heap-allocated C string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `text` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_text_clean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_text_clean(byte* text);

        /// <summary>
        ///  Remove newlines and collapse whitespace to single spaces.
        ///
        ///  Converts multi-line text into a single normalized line.
        ///
        ///  # Returns
        ///
        ///  Heap-allocated C string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `text` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_text_remove_newlines", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_text_remove_newlines(byte* text);

        /// <summary>
        ///  Trim text so its UTF-8 encoded size does not exceed `nbytes`.
        ///
        ///  Multi-byte characters that would be split are dropped entirely.
        ///  Leading/trailing whitespace is stripped from the result.
        ///
        ///  # Returns
        ///
        ///  Heap-allocated C string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `text` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_text_trim", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_text_trim(byte* text, nuint nbytes);

        /// <summary>
        ///  Normalize and simplify text for similarity hashing.
        ///
        ///  Applies NFD normalization, lowercasing, removes whitespace and characters
        ///  in Unicode categories C (control), M (mark), and P (punctuation), then
        ///  recombines with NFKC normalization.
        ///
        ///  # Returns
        ///
        ///  Heap-allocated C string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `text` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_text_collapse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_text_collapse(byte* text);

        /// <summary>
        ///  Encode bytes as base64url (RFC 4648 section 5, no padding).
        ///
        ///  # Parameters
        ///
        ///  - `data`: pointer to raw byte data
        ///  - `data_len`: number of bytes
        ///
        ///  # Returns
        ///
        ///  Heap-allocated C string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `data` must point to a valid buffer of at least `data_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_encode_base64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_encode_base64(byte* data, nuint data_len);

        /// <summary>
        ///  Convert a JSON string into a `data:` URL with JCS canonicalization.
        ///
        ///  Uses `application/ld+json` media type when the JSON contains an `@context`
        ///  key, otherwise `application/json`.
        ///
        ///  # Returns
        ///
        ///  Heap-allocated C string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  `json` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_json_to_data_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_json_to_data_url(byte* json);

        /// <summary>
        ///  Encode raw ISCC header components and digest into a base32 ISCC unit string.
        ///
        ///  Takes integer type identifiers and a raw digest, returns a base32-encoded
        ///  ISCC unit string (without "ISCC:" prefix).
        ///
        ///  # Parameters
        ///
        ///  - `mtype`: MainType enum value (0–7)
        ///  - `stype`: SubType enum value (0–7)
        ///  - `version`: Version enum value
        ///  - `bit_length`: bit length of the digest (multiple of 32)
        ///  - `digest`: pointer to raw digest bytes
        ///  - `digest_len`: number of bytes in the digest buffer
        ///
        ///  # Returns
        ///
        ///  Heap-allocated C string on success, `NULL` on error.
        ///  Caller must free with `iscc_free_string()`.
        ///
        ///  # Safety
        ///
        ///  If `digest_len &gt; 0`, `digest` must point to a valid buffer of at least
        ///  `digest_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_encode_component", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_encode_component(byte mtype, byte stype, byte version, uint bit_length, byte* digest, nuint digest_len);

        /// <summary>
        ///  Generate a composite ISCC-CODE from a file path (Data-Code + Instance-Code).
        ///
        ///  Single-pass file I/O feeds both DataHasher and InstanceHasher, then composes
        ///  the ISCC-CODE internally.
        ///
        ///  # Parameters
        ///
        ///  - `path`: null-terminated UTF-8 file path
        ///  - `bits`: hash bit length (typically 64)
        ///  - `wide`: if true, use 256-bit combination for ISCC-CODE
        ///  - `add_units`: if true, include individual Data-Code and Instance-Code strings
        ///
        ///  # Returns
        ///
        ///  `IsccSumCodeResult` struct. Check `ok` to determine success.
        ///  Caller must free with `iscc_free_sum_code_result()`.
        ///
        ///  # Safety
        ///
        ///  `path` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_gen_sum_code_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern IsccSumCodeResult iscc_gen_sum_code_v0(byte* path, uint bits, [MarshalAs(UnmanagedType.U1)] bool wide, [MarshalAs(UnmanagedType.U1)] bool add_units);

        /// <summary>
        ///  Free an `IsccSumCodeResult` previously returned by `iscc_gen_sum_code_v0`.
        ///
        ///  Releases the `iscc`, `datahash` strings, and `units` array. No-op for NULL pointers.
        ///
        ///  # Safety
        ///
        ///  `result` must be a value returned by `iscc_gen_sum_code_v0`.
        ///  Each result must only be freed once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_free_sum_code_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_free_sum_code_result(IsccSumCodeResult result);

        /// <summary>
        ///  Decode an ISCC unit string into header components and raw digest.
        ///
        ///  Returns an `IsccDecodeResult` struct. Check `ok` to determine success.
        ///  Strips an optional "ISCC:" prefix before decoding.
        ///
        ///  # Returns
        ///
        ///  `IsccDecodeResult` with decoded fields. On error, `ok` is `false`.
        ///  Caller must free with `iscc_free_decode_result()`.
        ///
        ///  # Safety
        ///
        ///  `iscc` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_decode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern IsccDecodeResult iscc_decode(byte* iscc);

        /// <summary>
        ///  Free an `IsccDecodeResult` previously returned by `iscc_decode`.
        ///
        ///  Releases the digest buffer if non-null. No-op if digest is already null.
        ///
        ///  # Safety
        ///
        ///  `result` must be a value returned by `iscc_decode`.
        ///  Each result must only be freed once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_free_decode_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_free_decode_result(IsccDecodeResult result);

        /// <summary>
        ///  Run all conformance tests against vendored test vectors.
        ///
        ///  Returns `true` if all tests pass, `false` if any fail.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_conformance_selftest", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool iscc_conformance_selftest();

        /// <summary>
        ///  Decompose a composite ISCC-CODE into individual ISCC-UNITs.
        ///
        ///  Accepts a normalized ISCC-CODE or concatenated ISCC-UNIT sequence.
        ///  The optional "ISCC:" prefix is stripped before decoding.
        ///  Returns a NULL-terminated array of heap-allocated C strings.
        ///
        ///  # Returns
        ///
        ///  NULL-terminated array on success, `NULL` on error (check `iscc_last_error()`).
        ///  Caller must free with `iscc_free_string_array()`.
        ///
        ///  # Safety
        ///
        ///  `iscc_code` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_decompose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte** iscc_decompose(byte* iscc_code);

        /// <summary>
        ///  Generate sliding window n-grams from a string.
        ///
        ///  Returns a NULL-terminated array of overlapping substrings of `width`
        ///  Unicode characters, advancing by one character at a time.
        ///
        ///  # Returns
        ///
        ///  NULL-terminated array on success, `NULL` on error (check `iscc_last_error()`).
        ///  Caller must free with `iscc_free_string_array()`.
        ///
        ///  # Safety
        ///
        ///  `seq` must point to a valid null-terminated UTF-8 string, or be null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_sliding_window", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte** iscc_sliding_window(byte* seq, uint width);

        /// <summary>
        ///  Compute a SimHash digest from an array of byte digests.
        ///
        ///  The output length matches the input digest length (e.g., 4-byte digests
        ///  produce a 4-byte SimHash). Returns an empty 32-byte buffer for empty input.
        ///
        ///  # Parameters
        ///
        ///  - `digests`: array of pointers to digest byte arrays
        ///  - `digest_lens`: array of lengths for each digest
        ///  - `num_digests`: number of digests
        ///
        ///  # Returns
        ///
        ///  `IsccByteBuffer` with the SimHash result. On error, `.data` is `NULL`.
        ///  Caller must free with `iscc_free_byte_buffer()`.
        ///
        ///  # Safety
        ///
        ///  - `digests` must point to an array of `num_digests` valid byte pointers
        ///  - `digest_lens` must point to an array of `num_digests` lengths
        ///  - Each `digests[i]` must be valid for `digest_lens[i]` bytes
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_alg_simhash", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern IsccByteBuffer iscc_alg_simhash(byte** digests, nuint* digest_lens, nuint num_digests);

        /// <summary>
        ///  Compute a 256-bit MinHash digest from 32-bit integer features.
        ///
        ///  Uses 64 universal hash functions with bit-interleaved compression to
        ///  produce a 32-byte similarity-preserving digest.
        ///
        ///  # Parameters
        ///
        ///  - `features`: pointer to `u32` feature values
        ///  - `features_len`: number of features
        ///
        ///  # Returns
        ///
        ///  `IsccByteBuffer` with 32 bytes. On error, `.data` is `NULL`.
        ///  Caller must free with `iscc_free_byte_buffer()`.
        ///
        ///  # Safety
        ///
        ///  `features` must point to a valid buffer of at least `features_len` `u32` elements.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_alg_minhash_256", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern IsccByteBuffer iscc_alg_minhash_256(uint* features, nuint features_len);

        /// <summary>
        ///  Split data into content-defined chunks using gear rolling hash.
        ///
        ///  Returns at least one chunk (empty bytes for empty input). When `utf32`
        ///  is true, aligns cut points to 4-byte boundaries.
        ///
        ///  # Parameters
        ///
        ///  - `data`: pointer to raw byte data
        ///  - `data_len`: number of bytes
        ///  - `utf32`: if true, align cuts to 4-byte boundaries
        ///  - `avg_chunk_size`: target average chunk size in bytes
        ///
        ///  # Returns
        ///
        ///  `IsccByteBufferArray` with chunks. On error, `.buffers` is `NULL`.
        ///  Caller must free with `iscc_free_byte_buffer_array()`.
        ///
        ///  # Safety
        ///
        ///  `data` must point to a valid buffer of at least `data_len` bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_alg_cdc_chunks", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern IsccByteBufferArray iscc_alg_cdc_chunks(byte* data, nuint data_len, [MarshalAs(UnmanagedType.U1)] bool utf32, uint avg_chunk_size);

        /// <summary>
        ///  Compute a similarity-preserving hash from video frame signatures.
        ///
        ///  Returns raw bytes of length `bits / 8`. Errors if `frame_sigs` is empty.
        ///
        ///  # Parameters
        ///
        ///  - `frame_sigs`: array of pointers to frame signature arrays (`i32`)
        ///  - `frame_lens`: array of lengths for each frame signature
        ///  - `num_frames`: number of frames
        ///  - `bits`: hash bit length (typically 64)
        ///
        ///  # Returns
        ///
        ///  `IsccByteBuffer` with the hash result. On error, `.data` is `NULL`.
        ///  Caller must free with `iscc_free_byte_buffer()`.
        ///
        ///  # Safety
        ///
        ///  - `frame_sigs` must point to an array of `num_frames` valid pointers
        ///  - `frame_lens` must point to an array of `num_frames` lengths
        ///  - Each `frame_sigs[i]` must be valid for `frame_lens[i]` `i32` elements
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_soft_hash_video_v0", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern IsccByteBuffer iscc_soft_hash_video_v0(int** frame_sigs, nuint* frame_lens, nuint num_frames, uint bits);

        /// <summary>
        ///  Create a new streaming Data-Code hasher.
        ///
        ///  Returns an opaque pointer. The caller must eventually call
        ///  `iscc_data_hasher_free()` to release the memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_data_hasher_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiDataHasher* iscc_data_hasher_new();

        /// <summary>
        ///  Push data into a streaming DataHasher.
        ///
        ///  Returns `true` on success, `false` on error (e.g., already finalized
        ///  or NULL pointer). Check `iscc_last_error()` for the error message.
        ///
        ///  # Safety
        ///
        ///  - `hasher` must be a valid pointer from `iscc_data_hasher_new()`, or NULL.
        ///  - `data` must point to at least `data_len` valid bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_data_hasher_update", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool iscc_data_hasher_update(FfiDataHasher* hasher, byte* data, nuint data_len);

        /// <summary>
        ///  Finalize a streaming DataHasher and return an ISCC string.
        ///
        ///  Consumes the inner hasher state. After this call, subsequent `update`
        ///  or `finalize` calls will fail. The caller must still call
        ///  `iscc_data_hasher_free()` to release the wrapper, and `iscc_free_string()`
        ///  to release the returned string.
        ///
        ///  # Safety
        ///
        ///  `hasher` must be a valid pointer from `iscc_data_hasher_new()`, or NULL.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_data_hasher_finalize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_data_hasher_finalize(FfiDataHasher* hasher, uint bits);

        /// <summary>
        ///  Free a DataHasher previously created by `iscc_data_hasher_new()`.
        ///
        ///  NULL is a no-op. Each pointer must be freed exactly once.
        ///
        ///  # Safety
        ///
        ///  `hasher` must be a valid pointer from `iscc_data_hasher_new()`, or NULL.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_data_hasher_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_data_hasher_free(FfiDataHasher* hasher);

        /// <summary>
        ///  Create a new streaming Instance-Code hasher.
        ///
        ///  Returns an opaque pointer. The caller must eventually call
        ///  `iscc_instance_hasher_free()` to release the memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_instance_hasher_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiInstanceHasher* iscc_instance_hasher_new();

        /// <summary>
        ///  Push data into a streaming InstanceHasher.
        ///
        ///  Returns `true` on success, `false` on error (e.g., already finalized
        ///  or NULL pointer). Check `iscc_last_error()` for the error message.
        ///
        ///  # Safety
        ///
        ///  - `hasher` must be a valid pointer from `iscc_instance_hasher_new()`, or NULL.
        ///  - `data` must point to at least `data_len` valid bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_instance_hasher_update", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool iscc_instance_hasher_update(FfiInstanceHasher* hasher, byte* data, nuint data_len);

        /// <summary>
        ///  Finalize a streaming InstanceHasher and return an ISCC string.
        ///
        ///  Consumes the inner hasher state. After this call, subsequent `update`
        ///  or `finalize` calls will fail. The caller must still call
        ///  `iscc_instance_hasher_free()` to release the wrapper, and
        ///  `iscc_free_string()` to release the returned string.
        ///
        ///  # Safety
        ///
        ///  `hasher` must be a valid pointer from `iscc_instance_hasher_new()`, or NULL.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_instance_hasher_finalize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_instance_hasher_finalize(FfiInstanceHasher* hasher, uint bits);

        /// <summary>
        ///  Free an InstanceHasher previously created by `iscc_instance_hasher_new()`.
        ///
        ///  NULL is a no-op. Each pointer must be freed exactly once.
        ///
        ///  # Safety
        ///
        ///  `hasher` must be a valid pointer from `iscc_instance_hasher_new()`, or NULL.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_instance_hasher_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_instance_hasher_free(FfiInstanceHasher* hasher);

        /// <summary>
        ///  Free a string previously returned by any `iscc_gen_*` function.
        ///
        ///  # Safety
        ///
        ///  `ptr` must be a pointer returned by one of the `iscc_gen_*_v0` functions,
        ///  or `NULL` (which is a no-op). Each pointer must only be freed once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_free_string(byte* ptr);

        /// <summary>
        ///  Free a NULL-terminated string array returned by `iscc_decompose` or
        ///  `iscc_sliding_window`.
        ///
        ///  Walks the array, freeing each string via `CString::from_raw`, then frees
        ///  the array itself. `NULL` is a no-op.
        ///
        ///  # Safety
        ///
        ///  `arr` must be a pointer returned by `iscc_decompose` or `iscc_sliding_window`,
        ///  or `NULL`. Each array must only be freed once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_free_string_array", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_free_string_array(byte** arr);

        /// <summary>
        ///  Free a byte buffer returned by `iscc_alg_simhash`, `iscc_alg_minhash_256`,
        ///  or `iscc_soft_hash_video_v0`.
        ///
        ///  No-op if `buf.data` is `NULL`.
        ///
        ///  # Safety
        ///
        ///  `buf` must be a value returned by one of the algorithm primitive functions.
        ///  Each buffer must only be freed once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_free_byte_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_free_byte_buffer(IsccByteBuffer buf);

        /// <summary>
        ///  Free a byte buffer array returned by `iscc_alg_cdc_chunks`.
        ///
        ///  Frees each buffer's data, then the array itself. No-op if `arr.buffers`
        ///  is `NULL`.
        ///
        ///  # Safety
        ///
        ///  `arr` must be a value returned by `iscc_alg_cdc_chunks`.
        ///  Each array must only be freed once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_free_byte_buffer_array", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void iscc_free_byte_buffer_array(IsccByteBufferArray arr);

        /// <summary>
        ///  Return the last error message from the current thread.
        ///
        ///  Returns a pointer to a null-terminated string valid until the next
        ///  `iscc_gen_*` call on the same thread. Returns `NULL` if no error
        ///  has occurred.
        ///
        ///  The returned pointer must NOT be freed by the caller.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "iscc_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* iscc_last_error();


    }

    /// <summary>
    ///  Heap-allocated byte buffer returned to C callers.
    ///
    ///  On success, `data` points to a contiguous byte array of `len` bytes.
    ///  On error, `data` is `NULL` and `len` is 0. Callers must free with
    ///  `iscc_free_byte_buffer()`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IsccByteBuffer
    {
        /// <summary>
        ///  Pointer to the byte data (`NULL` if error).
        /// </summary>
        public byte* data;
        /// <summary>
        ///  Number of bytes.
        /// </summary>
        public nuint len;
    }

    /// <summary>
    ///  Array of byte buffers (for `iscc_alg_cdc_chunks`).
    ///
    ///  Contains `count` elements pointed to by `buffers`. Callers must free
    ///  with `iscc_free_byte_buffer_array()`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IsccByteBufferArray
    {
        /// <summary>
        ///  Pointer to array of `IsccByteBuffer` elements.
        /// </summary>
        public IsccByteBuffer* buffers;
        /// <summary>
        ///  Number of buffers.
        /// </summary>
        public nuint count;
    }

    /// <summary>
    ///  Result of `gen_sum_code_v0` — composite Data+Instance ISCC-CODE with file metadata.
    ///
    ///  On success, `ok` is `true` and all fields are populated.
    ///  On error, `ok` is `false`, string pointers are `NULL`, and `filesize` is 0.
    ///  Caller must free with `iscc_free_sum_code_result()`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IsccSumCodeResult
    {
        /// <summary>
        ///  Whether the operation succeeded.
        /// </summary>
        [MarshalAs(UnmanagedType.U1)] public bool ok;
        /// <summary>
        ///  Composite ISCC-CODE string (heap-allocated, caller frees via `iscc_free_sum_code_result`).
        /// </summary>
        public byte* iscc;
        /// <summary>
        ///  Hex-encoded BLAKE3 multihash of the file (heap-allocated).
        /// </summary>
        public byte* datahash;
        /// <summary>
        ///  Byte length of the file.
        /// </summary>
        public ulong filesize;
        /// <summary>
        ///  NULL-terminated array of Data-Code and Instance-Code ISCC strings, or NULL.
        /// </summary>
        public byte** units;
    }

    /// <summary>
    ///  Result of decoding an ISCC unit string.
    ///
    ///  On success, `ok` is `true` and all fields are populated.
    ///  On error, `ok` is `false` and all fields are zeroed (check `iscc_last_error()`).
    ///  Caller must free with `iscc_free_decode_result()`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IsccDecodeResult
    {
        /// <summary>
        ///  Whether the decode succeeded.
        /// </summary>
        [MarshalAs(UnmanagedType.U1)] public bool ok;
        /// <summary>
        ///  MainType enum value (0–7).
        /// </summary>
        public byte maintype;
        /// <summary>
        ///  SubType enum value (0–7).
        /// </summary>
        public byte subtype;
        /// <summary>
        ///  Version enum value.
        /// </summary>
        public byte version;
        /// <summary>
        ///  Length index from the header.
        /// </summary>
        public byte length;
        /// <summary>
        ///  Raw digest bytes truncated to the encoded bit-length.
        /// </summary>
        public IsccByteBuffer digest;
    }

    /// <summary>
    ///  Opaque FFI wrapper around `iscc_lib::DataHasher`.
    ///
    ///  Enforces finalize-once semantics via `Option&lt;Inner&gt;`. Not `#[repr(C)]` —
    ///  C callers interact only through function pointers.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct FfiDataHasher
    {
    }

    /// <summary>
    ///  Opaque FFI wrapper around `iscc_lib::InstanceHasher`.
    ///
    ///  Enforces finalize-once semantics via `Option&lt;Inner&gt;`. Not `#[repr(C)]` —
    ///  C callers interact only through function pointers.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct FfiInstanceHasher
    {
    }



}
