# /// script
# requires-python = "==3.14.*"
# dependencies = []
# ///
"""Generate the vendored Unicode 16.0.0 case-classification tables for iscc-lib.

The Rust core lowercases `text_collapse` input with a `Final_Sigma` decision driven
by vendored Unicode 16.0.0 ``Cased`` / ``Case_Ignorable`` tables instead of
`str::to_lowercase()`'s compiler-shipped tables (rustc 1.97 ships Unicode 17.0,
which reclassified U+0295 from `Ll` to `Lo`). This script produces the data module
backing that case-property freeze: it derives both properties behaviourally from
CPython 3.14's `str.lower()` (whose `unicodedata` is pinned to Unicode 16.0.0 data),
merges each property into maximal inclusive ranges, verifies the known invariants of
the 16.0.0 tables, and writes the data-only Rust module
``crates/iscc-lib/src/utils/unicode16_case.rs``.

The two behavioural probes read the exact predicates CPython's
``handle_capital_sigma`` consults: ``(ch + SIGMA).lower()`` ends in final sigma iff
``ch`` is ``Cased`` and not ``Case_Ignorable``; ``("A" + ch + SIGMA).lower()`` ends
in final sigma iff ``ch`` is ``Cased`` or ``Case_Ignorable``. ``CASED_RANGES`` is
therefore ``Cased`` restricted to code points that are not ``Case_Ignorable`` — an
unobservable restriction, because the `Final_Sigma` scan skips case-ignorables
before ever testing ``Cased``, in CPython and in the Rust port alike.

The output is deterministic — rerunning the script on an up-to-date checkout leaves
the working tree unchanged.

Usage:
    uv run --script scripts/gen_unicode16_case.py
"""

from __future__ import annotations

import unicodedata
from itertools import pairwise
from pathlib import Path

# Known shape of the Unicode 16.0.0 case tables; a mismatch means the interpreter
# did not deliver 16.0.0 data and the output must not be written.
EXPECTED_CASED_RANGE_COUNT = 152
EXPECTED_CASED_CODE_POINT_COUNT = 4_311
EXPECTED_CASE_IGNORABLE_RANGE_COUNT = 452
EXPECTED_CASE_IGNORABLE_CODE_POINT_COUNT = 2_749

SIGMA = chr(0x03A3)  # GREEK CAPITAL LETTER SIGMA
FINAL = chr(0x03C2)  # GREEK SMALL LETTER FINAL SIGMA

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "crates/iscc-lib/src/utils/unicode16_case.rs"
)

HEADER = """\
//! `Cased` / `Case_Ignorable` classification frozen at Unicode 16.0.0.
//!
//! Generated by `scripts/gen_unicode16_case.py` — do not edit by hand.
//! Regenerate with `uv run --script scripts/gen_unicode16_case.py`.
//!
//! Unicode data version: 16.0.0 (from CPython 3.14's `unicodedata`). The tables
//! drive the `Final_Sigma` condition in `to_lowercase_unicode16` so that the
//! decision never depends on the Unicode tables the Rust compiler ships.
//! `CASED_RANGES` holds `Cased` restricted to code points that are **not**
//! `Case_Ignorable` (152 ranges covering 4,311 code points) — an unobservable
//! restriction, because the `Final_Sigma` scan skips case-ignorable code points
//! before ever testing `Cased`. `CASE_IGNORABLE_RANGES` holds `Case_Ignorable`
//! (452 ranges covering 2,749 code points).
"""


def collect_case_ranges() -> tuple[list[tuple[int, int]], list[tuple[int, int]]]:
    """Derive `Cased` and `Case_Ignorable` ranges from `str.lower()` behaviour."""
    cased_ranges: list[tuple[int, int]] = []
    ignorable_ranges: list[tuple[int, int]] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue  # surrogates: unreachable through &str input
        ch = chr(cp)
        a = (ch + SIGMA).lower().endswith(FINAL)  # Cased and not Case_Ignorable
        b = ("A" + ch + SIGMA).lower().endswith(FINAL)  # Cased or Case_Ignorable
        if a:
            append_to_ranges(cased_ranges, cp)
        elif b:
            append_to_ranges(ignorable_ranges, cp)
    return cased_ranges, ignorable_ranges


def append_to_ranges(ranges: list[tuple[int, int]], cp: int) -> None:
    """Extend the last maximal inclusive range with `cp` or start a fresh one."""
    if ranges and ranges[-1][1] == cp - 1:
        ranges[-1] = (ranges[-1][0], cp)
    else:
        ranges.append((cp, cp))


def check_invariants(
    cased: list[tuple[int, int]], ignorable: list[tuple[int, int]]
) -> None:
    """Fail loudly if the tables do not match the known Unicode 16.0.0 shape."""
    check_table_shape(
        "CASED_RANGES",
        cased,
        EXPECTED_CASED_RANGE_COUNT,
        EXPECTED_CASED_CODE_POINT_COUNT,
    )
    check_table_shape(
        "CASE_IGNORABLE_RANGES",
        ignorable,
        EXPECTED_CASE_IGNORABLE_RANGE_COUNT,
        EXPECTED_CASE_IGNORABLE_CODE_POINT_COUNT,
    )
    if not any(lo <= 0x0295 <= hi for lo, hi in cased):
        raise SystemExit("U+0295 must be Cased in Unicode 16.0.0")
    for name, ranges in (("cased", cased), ("case-ignorable", ignorable)):
        if any(lo <= 0xFFFF <= hi for lo, hi in ranges):
            raise SystemExit(f"the sentinel U+FFFF must not be {name}")


def check_table_shape(
    name: str, ranges: list[tuple[int, int]], expected_ranges: int, expected_total: int
) -> None:
    """Verify range count, code point count, and sorted/non-adjacent form."""
    if len(ranges) != expected_ranges:
        raise SystemExit(
            f"{name}: expected {expected_ranges} ranges, got {len(ranges)}"
        )
    total = sum(hi - lo + 1 for lo, hi in ranges)
    if total != expected_total:
        raise SystemExit(f"{name}: expected {expected_total} code points, got {total}")
    for (lo, hi), (next_lo, _) in pairwise(ranges):
        if lo > hi:
            raise SystemExit(f"{name}: inverted range (0x{lo:04X}, 0x{hi:04X})")
        if hi + 1 >= next_lo:
            raise SystemExit(
                f"{name}: ranges not sorted/non-adjacent at 0x{hi:04X} -> 0x{next_lo:04X}"
            )


def render_module(
    cased: list[tuple[int, int]], ignorable: list[tuple[int, int]]
) -> str:
    """Render the data-only Rust module in rustfmt-stable form."""
    parts = [HEADER]
    for doc, name, ranges in (
        (
            (
                "Maximal inclusive `(lo, hi)` ranges of code points that are `Cased` and\n"
                "/// not `Case_Ignorable` in Unicode 16.0.0."
            ),
            "CASED_RANGES",
            cased,
        ),
        (
            (
                "Maximal inclusive `(lo, hi)` ranges of code points that are\n"
                "/// `Case_Ignorable` in Unicode 16.0.0."
            ),
            "CASE_IGNORABLE_RANGES",
            ignorable,
        ),
    ):
        lines = [f"\n/// {doc}"]
        lines.append(f"pub(crate) const {name}: [(u32, u32); {len(ranges)}] = [")
        for lo, hi in ranges:
            lines.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
        lines.append("];")
        parts.append("\n".join(lines) + "\n")
    return "".join(parts)


def main() -> None:
    """Generate, verify, and write the vendored case tables."""
    if unicodedata.unidata_version != "16.0.0":
        raise SystemExit(f"need Unicode 16.0.0 data, got {unicodedata.unidata_version}")
    cased, ignorable = collect_case_ranges()
    check_invariants(cased, ignorable)
    OUTPUT_PATH.write_text(
        render_module(cased, ignorable), encoding="utf-8", newline="\n"
    )
    print(
        f"wrote {OUTPUT_PATH} ({len(cased)} cased + {len(ignorable)} ignorable ranges)"
    )


if __name__ == "__main__":
    main()
