# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Generate the C header of Unicode 16.0.0 boundary vectors for the iscc-ffi C test.

Renders the canonical fixture ``crates/iscc-lib/tests/unicode_boundary.json`` into
``crates/iscc-ffi/tests/unicode_boundary_vectors.h`` so the C test program
``crates/iscc-ffi/tests/test_iscc.c`` can assert the declared-Unicode-version freeze
rule through the C ABI without a JSON parser. Every non-ASCII UTF-8 byte is emitted
as a 3-digit octal escape: C hex escapes are greedy and unbounded (``\\xF0`` swallows
any hex digit that follows), while octal escapes stop after 3 digits, so the header
stays pure ASCII and parses unambiguously. The drift gate
``tests/test_gen_ffi_boundary_vectors.py`` asserts the tracked header matches a
fresh render byte for byte.

The output is deterministic — rerunning the script on an up-to-date checkout leaves
the working tree unchanged.

Usage:
    uv run --script scripts/gen_ffi_boundary_vectors.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = REPO_ROOT / "crates/iscc-lib/tests/unicode_boundary.json"
OUTPUT_PATH = REPO_ROOT / "crates/iscc-ffi/tests/unicode_boundary_vectors.h"

# The declared Unicode data version; a fixture carrying any other version must
# fail closed rather than silently rendering vectors for a different contract.
UNICODE_DATA_VERSION = "16.0.0"

# Section name -> (count macro, array identifier) as consumed by test_iscc.c.
SECTIONS = {
    "text_clean": ("ISCC_TEXT_CLEAN_VECTOR_COUNT", "iscc_text_clean_vectors"),
    "text_collapse": ("ISCC_TEXT_COLLAPSE_VECTOR_COUNT", "iscc_text_collapse_vectors"),
}

HEADER_PREAMBLE = """\
/* Generated by scripts/gen_ffi_boundary_vectors.py - DO NOT EDIT.
 *
 * Unicode 16.0.0 boundary vectors rendered from
 * crates/iscc-lib/tests/unicode_boundary.json. Non-ASCII UTF-8 bytes are
 * emitted as 3-digit octal escapes (never hex: C hex escapes are greedy and
 * unbounded, octal escapes stop after 3 digits).
 *
 * Regenerate with: uv run --script scripts/gen_ffi_boundary_vectors.py
 */
#ifndef ISCC_UNICODE_BOUNDARY_VECTORS_H
#define ISCC_UNICODE_BOUNDARY_VECTORS_H

#define ISCC_UNICODE_DATA_VERSION "16.0.0"

struct iscc_unicode_boundary_vector {
    const char *name;
    const char *input;
    const char *expected;
};
"""

HEADER_POSTAMBLE = "#endif /* ISCC_UNICODE_BOUNDARY_VECTORS_H */\n"


def escape_c_string(text: str) -> str:
    """Render text as the pure-ASCII body of a C string literal.

    Printable ASCII passes through (with double quote and backslash escaped);
    every other byte of the UTF-8 encoding becomes a 3-digit octal escape.
    """
    parts = []
    for byte in text.encode("utf-8"):
        if byte == 0x22:
            parts.append('\\"')
        elif byte == 0x5C:
            parts.append("\\\\")
        elif 0x20 <= byte <= 0x7E:
            parts.append(chr(byte))
        else:
            parts.append(f"\\{byte:03o}")
    return "".join(parts)


def render_section(section: str, cases: dict) -> str:
    """Render one fixture section as a count macro plus a vector array."""
    macro, array = SECTIONS[section]
    lines = [f"#define {macro} {len(cases)}"]
    lines.append(
        f"static const struct iscc_unicode_boundary_vector {array}[{macro}] = {{"
    )
    for name, case in cases.items():
        inputs = case["inputs"]
        if len(inputs) != 1:
            raise SystemExit(f"{section}/{name}: expected exactly 1 input")
        lines.append(f'    {{"{escape_c_string(name)}",')
        lines.append(f'     "{escape_c_string(inputs[0])}",')
        lines.append(f'     "{escape_c_string(case["outputs"]["result"])}"}},')
    lines.append("};")
    return "\n".join(lines) + "\n"


def render(fixture_path: Path) -> str:
    """Render the canonical boundary fixture into the full C header text."""
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    version = fixture.get("_metadata", {}).get("unicode_data_version")
    if version != UNICODE_DATA_VERSION:
        raise SystemExit(
            f"fixture declares unicode_data_version {version!r}, "
            f"expected {UNICODE_DATA_VERSION!r}"
        )
    blocks = [HEADER_PREAMBLE]
    for section in SECTIONS:
        cases = fixture.get(section)
        if not cases:
            raise SystemExit(f"fixture section {section!r} is missing or empty")
        blocks.append(render_section(section, cases))
    blocks.append(HEADER_POSTAMBLE)
    header = "\n".join(blocks)
    if not header.isascii():
        raise SystemExit("rendered header is not pure ASCII")
    return header


def main() -> None:
    """Render the fixture and write the tracked C header."""
    header = render(FIXTURE_PATH)
    OUTPUT_PATH.write_text(header, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
