# /// script
# requires-python = ">=3.10"
# dependencies = ["unicodedata2==16.0.0"]
# ///
"""Generate the vendored Unicode 16.0.0 unassigned-range table for iscc-lib.

The Rust core strips code points that are unassigned in Unicode 16.0.0 (the declared
Unicode data version, see `.claude/context/specs/rust-core.md`) from text input before
any normalization or category lookup. This script produces the data module backing that
freeze rule: it classifies every code point with `unicodedata2` pinned to Unicode
16.0.0 data, merges unassigned (general category ``Cn``) code points into maximal
inclusive ranges, verifies the known invariants of the 16.0.0 table, and writes the
data-only Rust module ``crates/iscc-lib/src/utils/unicode16.rs``.

The output is deterministic — rerunning the script on an up-to-date checkout leaves
the working tree unchanged.

Usage:
    uv run --script scripts/gen_unicode16_unassigned.py
"""

from __future__ import annotations

from itertools import pairwise
from pathlib import Path

import unicodedata2

# Known shape of the Unicode 16.0.0 Cn table; a mismatch means the pinned
# `unicodedata2` did not deliver 16.0.0 data and the output must not be written.
EXPECTED_RANGE_COUNT = 731
EXPECTED_CODE_POINT_COUNT = 819_533
EXPECTED_FIRST_RANGE = (0x0378, 0x0379)

OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent / "crates/iscc-lib/src/utils/unicode16.rs"
)

HEADER = """\
//! Code points unassigned in Unicode 16.0.0.
//!
//! Generated by `scripts/gen_unicode16_unassigned.py` — do not edit by hand.
//! Regenerate with `uv run --script scripts/gen_unicode16_unassigned.py`.
//!
//! Unicode data version: 16.0.0 (from `unicodedata2==16.0.0`). The table holds
//! all maximal inclusive ranges of code points with general category `Cn`
//! (unassigned) in Unicode 16.0.0: 731 ranges covering 819,533 code points.

/// Maximal inclusive `(lo, hi)` ranges of code points unassigned in Unicode 16.0.0.
"""


def collect_unassigned_ranges() -> list[tuple[int, int]]:
    """Merge all Unicode 16.0.0 ``Cn`` code points into maximal inclusive ranges."""
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    prev = 0
    for cp in range(0x110000):
        if unicodedata2.category(chr(cp)) == "Cn":
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            ranges.append((start, prev))
            start = None
    if start is not None:
        ranges.append((start, prev))
    return ranges


def check_invariants(ranges: list[tuple[int, int]]) -> None:
    """Fail loudly if the table does not match the known Unicode 16.0.0 shape."""
    if len(ranges) != EXPECTED_RANGE_COUNT:
        raise SystemExit(f"expected {EXPECTED_RANGE_COUNT} ranges, got {len(ranges)}")
    total = sum(hi - lo + 1 for lo, hi in ranges)
    if total != EXPECTED_CODE_POINT_COUNT:
        raise SystemExit(
            f"expected {EXPECTED_CODE_POINT_COUNT} code points, got {total}"
        )
    if ranges[0] != EXPECTED_FIRST_RANGE:
        raise SystemExit(
            f"expected first range {EXPECTED_FIRST_RANGE}, got {ranges[0]}"
        )
    for (lo, hi), (next_lo, _) in pairwise(ranges):
        if lo > hi:
            raise SystemExit(f"inverted range (0x{lo:04X}, 0x{hi:04X})")
        if hi + 1 >= next_lo:
            raise SystemExit(
                f"ranges not sorted/non-adjacent at 0x{hi:04X} -> 0x{next_lo:04X}"
            )


def render_module(ranges: list[tuple[int, int]]) -> str:
    """Render the data-only Rust module in rustfmt-stable form."""
    lines = [f"pub(crate) const UNASSIGNED_RANGES: [(u32, u32); {len(ranges)}] = ["]
    for lo, hi in ranges:
        lines.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
    lines.append("];")
    return HEADER + "\n".join(lines) + "\n"


def main() -> None:
    """Generate, verify, and write the vendored range table."""
    ranges = collect_unassigned_ranges()
    check_invariants(ranges)
    OUTPUT_PATH.write_text(render_module(ranges), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH} ({len(ranges)} ranges)")


if __name__ == "__main__":
    main()
