/* Generated by scripts/gen_ffi_boundary_vectors.py - DO NOT EDIT.
 *
 * Unicode 16.0.0 boundary vectors rendered from
 * crates/iscc-lib/tests/unicode_boundary.json. Non-ASCII UTF-8 bytes are
 * emitted as 3-digit octal escapes (never hex: C hex escapes are greedy and
 * unbounded, octal escapes stop after 3 digits).
 *
 * Regenerate with: uv run --script scripts/gen_ffi_boundary_vectors.py
 */
#ifndef ISCC_UNICODE_BOUNDARY_VECTORS_H
#define ISCC_UNICODE_BOUNDARY_VECTORS_H

#define ISCC_UNICODE_DATA_VERSION "16.0.0"

struct iscc_unicode_boundary_vector {
    const char *name;
    const char *input;
    const char *expected;
};

#define ISCC_TEXT_CLEAN_VECTOR_COUNT 7
static const struct iscc_unicode_boundary_vector iscc_text_clean_vectors[ISCC_TEXT_CLEAN_VECTOR_COUNT] = {
    {"test_0000_u1fae9_assigned_so_retained",
     "a\360\237\253\251b",
     "a\360\237\253\251b"},
    {"test_0001_u113c5_assigned_mc_retained",
     "a\360\221\217\205b",
     "a\360\221\217\205b"},
    {"test_0002_u20c1_unassigned_16_stripped",
     "a\342\203\201b",
     "ab"},
    {"test_0003_ua7f1_unassigned_16_stripped",
     "a\352\237\261b",
     "ab"},
    {"test_0004_seq_u0378_blocks_canonical_composition",
     "e\315\270\314\201",
     "e\314\201"},
    {"test_0005_seq_u0378_blocks_hangul_composition",
     "\341\204\200\315\270\341\205\241",
     "\341\204\200\341\205\241"},
    {"test_0006_seq_ua7f1_no_decomposition_leak",
     "e\352\237\261\314\201",
     "e\314\201"},
};

#define ISCC_TEXT_COLLAPSE_VECTOR_COUNT 5
static const struct iscc_unicode_boundary_vector iscc_text_collapse_vectors[ISCC_TEXT_COLLAPSE_VECTOR_COUNT] = {
    {"test_0000_u1fae9_assigned_so_retained",
     "a\360\237\253\251b",
     "a\360\237\253\251b"},
    {"test_0001_u113c5_assigned_mc_mark_dropped",
     "a\360\221\217\205b",
     "ab"},
    {"test_0002_u20c1_unassigned_16_stripped",
     "a\342\203\201b",
     "ab"},
    {"test_0003_ua7f1_unassigned_16_stripped",
     "a\352\237\261b",
     "ab"},
    {"test_0004_seq_u0378_preserves_final_sigma",
     "\316\221\316\243\315\270\316\222",
     "\316\261\317\202\316\262"},
};

#endif /* ISCC_UNICODE_BOUNDARY_VECTORS_H */
