"""Type stubs for the native Rust extension module `iscc._lowlevel`."""

def gen_meta_code_v0(
    name: str,
    description: str | None = None,
    meta: str | None = None,
    bits: int = 64,
) -> str: ...
def gen_text_code_v0(text: str, bits: int = 64) -> str: ...
def gen_image_code_v0(pixels: bytes, bits: int = 64) -> str: ...
def gen_audio_code_v0(cv: list[int], bits: int = 64) -> str: ...
def gen_video_code_v0(frame_sigs: list[list[int]], bits: int = 64) -> str: ...
def gen_mixed_code_v0(codes: list[str], bits: int = 64) -> str: ...
def gen_data_code_v0(data: bytes, bits: int = 64) -> str: ...
def gen_instance_code_v0(data: bytes, bits: int = 64) -> str: ...
def gen_iscc_code_v0(codes: list[str], wide: bool = False) -> str: ...
